spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/uchat-dev?characterEncoding=utf-8
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
    type: com.zaxxer.hikari.HikariDataSource


