mybatis:
    type-aliases-package: tk.mybatis.springboot.model
    mapper-locations: classpath:mappers/*.xml
mapper:
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
spring:
    profiles:
        active: dev
    datasource:
        hikari:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/uchat-dev?characterEncoding=utf-8
          data-username: root
          data-password: root
          minimum-idle: 5
          maximum-pool-size: 20
    type: com.zaxxer.hikari.HikariDataSource


